version: '3.8'

services:
  # PostgreSQL for storing backfill state
  postgres:
    image: postgres:15-alpine
    container_name: relay-monitor-postgres
    environment:
      POSTGRES_USER: relay
      POSTGRES_PASSWORD: relay
      POSTGRES_DB: backfiller_relay
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U relay -d backfiller_relay"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - relay-network

  # PostgreSQL Exporter for database metrics
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: relay-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://relay:relay@relay-monitor-postgres:5432/backfiller_relay?sslmode=disable"
      PG_EXPORTER_DISABLE_DEFAULT_METRICS: "false"
      PG_EXPORTER_DISABLE_SETTINGS_METRICS: "false"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/queries/queries.yaml"
    volumes:
      - ./monitoring/postgres-queries.yaml:/queries/queries.yaml:ro
    ports:
      - "9187:9187"
    networks:
      - relay-network
    depends_on:
      postgres:
        condition: service_healthy

  # Mock Ingester client that connects to relay
  mock-ingester:
    build:
      context: .
      dockerfile: test/mock-ingester/Dockerfile
    container_name: relay-monitor-ingester
    command: ["-relay", "relay-monitor:50051", "-stats", "5", "-ack", "100"]
    depends_on:
      relay:
        condition: service_started
    networks:
      - relay-network

  # The relay service
  relay:
    build:
      context: ..
      dockerfile: tradr-backfiller-relay/Dockerfile
    container_name: relay-monitor
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_DSN: "postgres://relay:relay@relay-monitor-postgres:5432/backfiller_relay?sslmode=disable"
      DATABASE_MAX_OPEN_CONNS: "75"
      DATABASE_MAX_IDLE_CONNS: "50"
      FIREHOSE_HOST: "wss://bsky.network"
      NSID_FILTER: "app.bsky.feed.post,app.bsky.graph.follow,app.bsky.actor.profile"
      GRPC_SERVER_PORT: "50051"
      RELAY_NAME: "relay-monitor"
      LOG_LEVEL: "debug"
      PARALLEL_BACKFILLS: "50"
      PARALLEL_RECORD_CREATES: "20"
      GRPC_MAX_MESSAGE_SIZE: "10485760"
      METRICS_PORT: "9090"
    ports:
      - "9090:9090"
      - "50051:50051"
      - "6060:6060"  # pprof profiling endpoint
    volumes:
      - ./config/config.yaml:/app/config/config.yaml:ro
    networks:
      - relay-network

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: relay-monitor-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - relay-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: relay-monitor-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/relay-dashboard.json
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - relay-network
    depends_on:
      - prometheus

networks:
  relay-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local