# Prometheus configuration for Tradr Backfiller Relay monitoring

global:
  # How frequently to scrape targets
  scrape_interval: 15s
  
  # How frequently to evaluate rules
  evaluation_interval: 15s
  
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager)
  external_labels:
    monitor: 'tradr-relay-monitor'
    environment: 'development'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
rule_files:
  # - "alerts.yml"
  # - "rules.yml"

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Scrape the Tradr Relay service
  - job_name: 'tradr-relay'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['relay:9090']
        labels:
          service: 'tradr-relay'
          instance: 'primary'

  # Optional: Scrape PostgreSQL exporter if you add one
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #       labels:
  #         service: 'postgres'

  # Optional: Scrape node exporter for system metrics
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         service: 'node'