# Tradr Backfiller Relay Configuration
# This file contains default configuration values
# Environment variables can override these settings

relay:
  name: "tradr-relay"
  max_retries: 3
  retry_backoff_ms: 1000

firehose:
  # AT Protocol relay WebSocket endpoint
  relay_host: "wss://bsky.network"
  
  # Filter for specific record types (e.g., "app.bsky." for Bluesky records only)
  nsid_filter: "app.bsky."
  
  # Optional sequencer for cursor management
  sequencer_url: ""
  
  # Reconnection settings (-1 for infinite retries)
  max_reconnect_attempts: -1
  reconnect_delay_ms: 5000

backfiller:
  # Number of concurrent repository backfills
  parallel_backfills: 10
  
  # Number of concurrent record operations per backfill
  parallel_record_creates: 100
  
  # Record type filter (usually same as firehose)
  nsid_filter: "app.bsky."
  
  # How often to checkpoint progress (number of operations)
  checkpoint_interval: 1000
  
  # Maximum operations to buffer during backfill
  buffer_size: 10000
  
  # How often to check for new backfill jobs (milliseconds)
  process_interval_ms: 1000

grpc:
  # Port for management gRPC server
  port: 50051
  
  # Maximum message size (10MB default)
  max_message_size: 10485760
  
  # Maximum concurrent streams per connection
  max_concurrent_streams: 100
  
  # Connection keepalive settings
  keepalive_time_sec: 30
  keepalive_timeout_sec: 10
  
  # TLS configuration (disabled by default)
  enable_tls: false
  tls_cert_file: ""
  tls_key_file: ""

# Ingester service addresses
# Multiple addresses for load balancing and redundancy
ingesters:
  - "localhost:50052"
  # - "ingester-2:50052"
  # - "ingester-3:50052"

database:
  # PostgreSQL connection string
  # Format: postgres://user:password@host:port/database?sslmode=disable
  dsn: "postgres://relay:relay@localhost:5432/backfiller_relay?sslmode=disable"
  
  # Connection pool settings
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime_min: 5

metrics:
  # Port for Prometheus metrics endpoint
  port: 9090
  
  # Path for metrics endpoint
  path: "/metrics"
  
  # Include Go runtime metrics
  enable_runtime_metrics: true

# Log level: debug, info, warn, error
log_level: "info"